server.servlet.session.timeout=2h
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
spring.flyway.locations=classpath:db/migration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
