server.servlet.session.timeout=30m
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
spring.flyway.locations=classpath:db/migration
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
