spring.application.name=demo
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/backend_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:MyP@ssw0rd}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.locations=classpath:db/migration
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.path=/
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.paths-to-match=/api/v1/auth/**
