server.servlet.session.timeout=8h
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=false
spring.flyway.locations=classpath:db/migration,classpath:db/seed
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
